# Generated by Django 5.2.6 on 2025-10-21 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Echo_app', '0002_perfilusuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='categorias_de_interesse',
            field=models.ManyToManyField(blank=True, related_name='perfis_interessados', to='Echo_app.categoria', verbose_name='Categorias de Interesse'),
        ),
    ]
