# Generated by Django 5.2.6 on 2025-10-28 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Echo_app', '0003_perfilusuario_categorias_de_interesse'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='noticias/', verbose_name='Imagem da Notícia'),
        ),
    ]
